program quipos;

uses
  windows,
  forms,
  classes,
  controls,
  sysutils,
  dialogs,
  uMain in 'uMain.pas' {frmmain},
  uPedido in 'uPedido.pas' {frmPedido},
  uLocalizarPedido in 'uLocalizarPedido.pas' {frmLocalizarPedido},
  usaida in 'usaida.pas' {frmsaida},
  uconsultapedido in 'uconsultapedido.pas' {frmConsultaPedido},
  uconsultarepresentante in 'uconsultarepresentante.pas' {frmConsultaRepresentante},
  uadntcliente in 'uadntcliente.pas' {frmAdntCliente},
  uadntfornecedor in 'uadntfornecedor.pas' {frmAdntFornecedor},
  uautpagto in 'uautpagto.pas' {frmAutPagto},
  ucondpagto in 'ucondpagto.pas' {frmCondPagto},
  uconsultaautpagto in 'uconsultaautpagto.pas' {frmConsultaAutpagto},
  uconsultacliente in 'uconsultacliente.pas' {frmConsultaCliente},
  uconsultaduplicata in 'uconsultaduplicata.pas' {frmConsultaDuplicata},
  uconsultaentrada in 'uconsultaentrada.pas' {frmConsultaEntrada},
  uconsultamovbancario in 'uconsultamovbancario.pas' {frmConsultaMovBancario},
  uconsultamovto in 'uconsultamovto.pas' {frmConsultaMovto},
  uconsultaProduto in 'uconsultaProduto.pas' {frmConsultaProduto},
  uconsultasaida in 'uconsultasaida.pas' {frmConsultaSaida},
  ulivro in 'ulivro.pas' {frmlivro},
  uconta in 'uconta.pas' {frmConta},
  uduplicata in 'uduplicata.pas' {frmDuplicata},
  uempresa in 'uempresa.pas' {frmEmpresa},
  uentrada in 'uentrada.pas' {frmentrada},
  umanagerduplicata in 'umanagerduplicata.pas' {frmManagerDuplicata},
  umanagerautpagto in 'umanagerautpagto.pas' {frmManagerAutPagto},
  urepresentante in 'urepresentante.pas' {frmRepresentante},
  umanagerproduto in 'umanagerproduto.pas' {frmManagerproduto},
  utpentrada in 'utpentrada.pas' {frmtpentrada},
  utpproduto in 'utpproduto.pas' {frmtpproduto},
  utpsaida in 'utpsaida.pas' {frmtpsaida},
  uFornecedor in 'uFornecedor.pas' {frmFornecedor},
  uProduto in 'uProduto.pas' {frmProduto},
  ulocalizarmovbancario in 'ulocalizarmovbancario.pas' {frmLocalizarMovBancario},
  ulocalizarCliente in 'ulocalizarCliente.pas' {frmLocalizarcliente},
  ulocalizar in 'ulocalizar.pas' {frmLocalizar},
  ubaixa in 'ubaixa.pas' {frmbaixa},
  ucliente in 'ucliente.pas' {frmCliente},
  ulocalizarsaida in 'ulocalizarsaida.pas' {frmLocalizarSaida},
  ulocalizarTransportadora in 'ulocalizarTransportadora.pas' {frmLocalizarTransportadora},
  ulocalizarproduto in 'ulocalizarproduto.pas' {frmLocalizarProduto},
  uexportarexcel in 'uexportarexcel.pas' {frmExporExcel},
  uNovoProduto in 'uNovoProduto.pas' {frmNovoProduto},
  uDtmMain in 'uDtmMain.pas' {dtmmain: TDataModule},
  ucheque in 'ucheque.pas' {frmcheque},
  ulocalizarcheque in 'ulocalizarcheque.pas' {frmLocalizarCheque},
  unovofornecedor in 'unovofornecedor.pas' {frmNovoFornecedor},
  uManageruser in 'uManageruser.pas' {frmManagerUser},
  uEtapa in 'uEtapa.pas' {frmEtapa},
  UfiltrarOrdServ in 'UfiltrarOrdServ.pas' {frmfiltrarOrdServ},
  uFuncionario in 'uFuncionario.pas' {frmFuncionario},
  ulocalizarContrato in 'ulocalizarContrato.pas' {frmLocalizarContrato},
  umudaretapa in 'umudaretapa.pas' {frmmudaretapa},
  ucontrato in 'ucontrato.pas' {frmContrato},
  uNovoEquipamento in 'uNovoEquipamento.pas' {frmNovoEquipamento},
  UdlgInfNumIntervencao in 'UdlgInfNumIntervencao.pas' {frmdlginfNumIntervencao},
  ulocalizarfornecedor in 'ulocalizarfornecedor.pas' {frmLocalizarFornecedor},
  uconsultacheque in 'uconsultacheque.pas' {frmConsultaCheque},
  utpaprovacao in 'utpaprovacao.pas' {frmtpaprovacao},
  uLocalizarAdntFornecedor in 'uLocalizarAdntFornecedor.pas' {frmLocalizarAdntFornecedor},
  uLocalizarAutPagto in 'uLocalizarAutPagto.pas' {frmLocalizarAutPagto},
  ulocalizarentrada in 'ulocalizarentrada.pas' {frmLocalizarEntrada},
  uinterbase in 'uinterbase.pas',
  utpordserv in 'utpordserv.pas' {frmtpordserv},
  uFaturamento in 'uFaturamento.pas' {frmFaturamento},
  uLocalizarFaturamento in 'uLocalizarFaturamento.pas' {frmLocalizarFaturamento},
  uNovoCliente in 'uNovoCliente.pas' {frmNovoCliente},
  untVersao in 'untVersao.pas' {frmVersao},
  uconsultasaidarecalcularpedidoqtatendida in 'uconsultasaidarecalcularpedidoqtatendida.pas',
  uLocalizarAdntCliente in 'uLocalizarAdntCliente.pas' {frmLocalizarAdntCliente},
  classeVersao in 'classeVersao.pas',
  classeempresa in 'classeempresa.pas',
  classemovbancario in 'classemovbancario.pas',
  classeRegistro in 'classeRegistro.pas',
  classeusuario in 'classeusuario.pas',
  classeform in 'classeform.pas',
  uXLConst in 'uXLConst.pas',
  uAdicionarListView in 'uAdicionarListView.pas',
  uanotacao in 'uanotacao.pas' {frmAnotacao},
  uAplicacao in 'uAplicacao.pas' {frmAplicacao},
  classeproduto in 'classeproduto.pas',
  classecliente in 'classecliente.pas',
  classefaturamento in 'classefaturamento.pas',
  classeadntcliente in 'classeadntcliente.pas',
  classecobranca in 'classecobranca.pas',
  classepagtocomissao in 'classepagtocomissao.pas',
  classeetapa in 'classeetapa.pas',
  classemensagem in 'classemensagem.pas',
  classeduplicata in 'classeduplicata.pas',
  uPedidoMaterial in 'uPedidoMaterial.pas' {frmPedidoMaterial},
  ClasseOrdServ in 'ClasseOrdServ.pas',
  uBaixaEstoque in 'uBaixaEstoque.pas' {frmBaixaEstoque},
  ClasseMain in 'ClasseMain.pas',
  uordserv1orcamentoavulso in 'uordserv1orcamentoavulso.pas',
  uordserv1orcamentocontrato in 'uordserv1orcamentocontrato.pas',
  uconsulta in 'uconsulta.pas' {frmconsulta},
  uprodutoinsercaocdbarras in 'uprodutoinsercaocdbarras.pas' {frmprodutoinsercaocdbarras},
  classearquivo in 'classearquivo.pas',
  classeequipamento in 'classeequipamento.pas',
  classecaixafinanceiro in 'classecaixafinanceiro.pas',
  classeconta in 'classeconta.pas',
  utpanotacao in 'utpanotacao.pas' {frmtpanotacao},
  uordserv1wordentregasemcomprovante in 'uordserv1wordentregasemcomprovante.pas',
  ulocalizarrim in 'ulocalizarrim.pas' {frmLocalizarRIM},
  classepedidomaterial in 'classepedidomaterial.pas',
  ugerarDevolucao in 'ugerarDevolucao.pas' {frmGerarDevolucao},
  classefornecedor in 'classefornecedor.pas',
  classetabirpf in 'classetabirpf.pas',
  classeentrada in 'classeentrada.pas',
  classesaida in 'classesaida.pas',
  classetransportadora in 'classetransportadora.pas',
  uentradaimportarxml in 'uentradaimportarxml.pas' {frmentradaimportarxml},
  ulogin in 'ulogin.pas' {frmLogin},
  classepedido in 'classepedido.pas',
  classeLivroFiscal in 'classeLivroFiscal.pas',
  classerpa in 'classerpa.pas',
  uvalidadocumento in 'uvalidadocumento.pas',
  classeLivroFiscalDigital in 'classeLivroFiscalDigital.pas',
  udlgRichEdit in 'udlgRichEdit.pas' {frmdlgrichedit},
  classeretornasql in 'classeretornasql.pas',
  ClasseConsiste in 'ClasseConsiste.pas',
  classegerar in 'classegerar.pas',
  classeregistrainformacao in 'classeregistrainformacao.pas',
  ulocalizarFuncionario in 'ulocalizarFuncionario.pas' {frmLocalizarFuncionario},
  uLocacao in 'uLocacao.pas' {frmlocacao},
  ulocalizarlocacao in 'ulocalizarlocacao.pas' {frmLocalizarLocacao},
  utplocacao in 'utplocacao.pas' {frmtplocacao},
  classenfe in 'classenfe.pas',
  classeadntfornecedor in 'classeadntfornecedor.pas',
  classerelatorio in 'classerelatorio.pas',
  ubaixaRequisicao in 'ubaixaRequisicao.pas' {frmBaixaRequisicao},
  ustrings in 'ustrings.pas',
  classeEndereco in 'classeEndereco.pas',
  classefuncionario in 'classefuncionario.pas',
  classerepresentante in 'classerepresentante.pas',
  classelocacao in 'classelocacao.pas',
  classerecalculocustomedio in 'classerecalculocustomedio.pas',
  uduplicataparcelamento in 'uduplicataparcelamento.pas' {frmdlgGerarParcelamentoDuplicata},
  classeconsulta in 'classeconsulta.pas',
  classeexecutasql in 'classeexecutasql.pas',
  umontarsql in 'umontarsql.pas',
  ulocalizartransporte in 'ulocalizartransporte.pas' {frmLocalizartransporte},
  uFaturamentoTipo in 'uFaturamentoTipo.pas' {frmFaturamentoTipo},
  uLocalizarOrdcompra in 'uLocalizarOrdcompra.pas' {frmLocalizarOrdCompra},
  uLocalizarMovto in 'uLocalizarMovto.pas' {frmLocalizarMovto},
  umanagerpedido in 'umanagerpedido.pas' {frmmanagerpedido},
  uPapel in 'uPapel.pas' {frmPapel},
  classeACBR in 'classeACBR.pas',
  uacbr in 'uacbr.pas' {frmsetacbr},
  uveiculo in 'uveiculo.pas' {frmVeiculo},
  classeadntclienterecalculosaldo in 'classeadntclienterecalculosaldo.pas',
  ulocalizarLivrop3 in 'ulocalizarLivrop3.pas' {frmLocalizarlp1a},
  udlgxmltotreeview in 'udlgxmltotreeview.pas' {frmdlgxmltotreeview},
  unumero in 'unumero.pas',
  utipo in 'utipo.pas',
  uprogressbar in 'uprogressbar.pas' {frmprogressbar},
  udatahora in 'udatahora.pas',
  uRichEdit in 'uRichEdit.pas' {frmRichEdit},
  uexibircampos in 'uexibircampos.pas' {frmexibircampos},
  uNovoTabela in 'uNovoTabela.pas' {frmNovoTabela},
  classesqlmontar in 'classesqlmontar.pas',
  uGerarOrdCompra in 'uGerarOrdCompra.pas' {frmGerarOrdCompra},
  uSelecionarEntrada in 'uSelecionarEntrada.pas' {frmSelecionarEntrada},
  classeDifAliquota in 'classeDifAliquota.pas',
  uDBMemo in 'uDBMemo.pas' {frmdbMemo},
  unovotransportadora in 'unovotransportadora.pas' {frmNovoTransportadora},
  ufrmStatus in 'ufrmStatus.pas' {frmstacbr},
  udlginutilizarnfe in 'udlginutilizarnfe.pas' {frmdlginutilizarnfe},
  ulocalizarcobranca in 'ulocalizarcobranca.pas' {frmlocalizarcobranca},
  uGrupos in 'uGrupos.pas' {frmGrupos},
  uUsuario in 'uUsuario.pas' {frmUsuario},
  uPermissao in 'uPermissao.pas' {frmPermissao},
  uNovaMensagem in 'uNovaMensagem.pas' {frmNovaMensagem},
  upara in 'upara.pas' {frmpara},
  ufaturamentogerarprodutomensalidade in 'ufaturamentogerarprodutomensalidade.pas',
  ufaturamentodlggerarprodutomensalidade in 'ufaturamentodlggerarprodutomensalidade.pas' {frmfaturamentodlggerarprodutomensalidade},
  uGerarCompra in 'uGerarCompra.pas' {frmgerarCompra},
  ureport in 'ureport.pas' {frmReport},
  ureplicacao in 'ureplicacao.pas',
  uregistroIb in 'uregistroIb.pas',
  ucorridaquimica in 'ucorridaquimica.pas' {frmcorridaquimica},
  ulocalizarcorridaquimica in 'ulocalizarcorridaquimica.pas' {frmLocalizarCorridaquimica},
  utppedido in 'utppedido.pas' {frmtppedido},
  uAssinaturaDigital in 'uAssinaturaDigital.pas' {frmAssinaturaDigital},
  ucaixafinanceiro in 'ucaixafinanceiro.pas' {frmcaixafinanceiro},
  udlgaprovarconciliado in 'udlgaprovarconciliado.pas' {frmdlgaprovarconciliado},
  umovbancario in 'umovbancario.pas' {frmmovbancario},
  classecondpagto in 'classecondpagto.pas',
  udlgdatabalanco in 'udlgdatabalanco.pas' {frmdlgdatabalanco},
  ucte in 'ucte.pas' {frmCTE},
  utpordcompra in 'utpordcompra.pas' {frmtpordcompra},
  classeordcompra in 'classeordcompra.pas',
  utppedidomaterial in 'utppedidomaterial.pas' {frmtppedidomaterial},
  utprim in 'utprim.pas' {frmtprim},
  uimprimirrelatoriopadrao in 'uimprimirrelatoriopadrao.pas',
  rptestoquecompleto in 'rptestoquecompleto.pas' {frmestoquecompleto},
  uimp_adntcliente_ficha_saldo in 'uimp_adntcliente_ficha_saldo.pas',
  uimp_adntcliente_saldo in 'uimp_adntcliente_saldo.pas',
  uimp_adntcliente_saldo_diario in 'uimp_adntcliente_saldo_diario.pas',
  uimp_cntcusto_consumo_semestral in 'uimp_cntcusto_consumo_semestral.pas',
  uimp_acompanhamento_venda in 'uimp_acompanhamento_venda.pas',
  uimp_corrida_certificado in 'uimp_corrida_certificado.pas',
  rptreferenciacruzada in 'rptreferenciacruzada.pas' {frmreferenciacruzada},
  ulocalizarcte in 'ulocalizarcte.pas' {frmLocalizarCTE},
  ulocalizarveiculo in 'ulocalizarveiculo.pas' {frmLocalizarVeiculo},
  uctereport in 'uctereport.pas' {frmctereport},
  unfereport in 'unfereport.pas' {frmnfereport},
  ucfop in 'ucfop.pas' {frmcfop},
  classesintegra in 'classesintegra.pas',
  uorcamento in 'uorcamento.pas' {frmOrcamento},
  ulocalizarorcamento in 'ulocalizarorcamento.pas' {frmLocalizarOrcamento},
  classeorcamento in 'classeorcamento.pas',
  uuf in 'uuf.pas' {frmUF},
  utporcamento in 'utporcamento.pas' {frmtporcamento},
  ucobranca in 'ucobranca.pas' {frmCobranca},
  urim in 'urim.pas' {frmrim},
  udlgselecionar in 'udlgselecionar.pas' {frmdlgselecionar},
  udlgcalculopeso in 'udlgcalculopeso.pas' {frmcalculopeso},
  utpfaturamento in 'utpfaturamento.pas' {frmtpfaturamento},
  uimp_extrato_conta in 'uimp_extrato_conta.pas',
  umovto in 'umovto.pas' {frmmovto},
  classemovto in 'classemovto.pas',
  utpequipamento in 'utpequipamento.pas' {frmtpequipamento},
  classequery in 'classequery.pas',
  uRotinas in 'uRotinas.pas',
  uconfiguracao in 'uconfiguracao.pas' {frmConfiguracao},
  uRegistro in 'uRegistro.pas',
  usystem in 'usystem.pas',
  uConstantes in 'uConstantes.pas',
  uProtector in 'uProtector.pas',
  ugerarpedido in 'ugerarpedido.pas' {frmdlgGerarPedido},
  classerim in 'classerim.pas',
  udlgfaturamentoproduto in 'udlgfaturamentoproduto.pas' {frmdlgfaturamentoproduto},
  udlgavaliacaoiqf in 'udlgavaliacaoiqf.pas' {frmdlgavaliacaoiqf},
  umarkupentrada in 'umarkupentrada.pas' {frmmarkupentrada},
  classeefdpiscofins in 'classeefdpiscofins.pas',
  classeemail in 'classeemail.pas',
  imp_sintetico_autpagto_cntcusto in 'imp_sintetico_autpagto_cntcusto.pas',
  classeordproducao in 'classeordproducao.pas',
  uordproducao in 'uordproducao.pas' {frmordproducao},
  classerecalculoestoqueterceiro in 'classerecalculoestoqueterceiro.pas',
  classecte in 'classecte.pas',
  ulocalizarordproducao in 'ulocalizarordproducao.pas' {frmLocalizarOrdProducao},
  uimp_fluxo_caixa in 'uimp_fluxo_caixa.pas',
  uativopiscofins in 'uativopiscofins.pas' {frmativopiscofins},
  uanalisecritica in 'uanalisecritica.pas' {frmdlganalisecritica},
  ucartacorrecao in 'ucartacorrecao.pas' {frmdlgcartacorrecao},
  uitsaidaimportacao in 'uitsaidaimportacao.pas' {frmdlgitsaidaimportacao},
  udlgdesenhoorcamento in 'udlgdesenhoorcamento.pas' {frmdlgdesenhoorcamento},
  urota in 'urota.pas' {frmrota},
  umanagerTarefa in 'umanagerTarefa.pas' {frmmanagertarefa},
  utarefa in 'utarefa.pas' {frmdlgtarefa},
  classecontrato in 'classecontrato.pas',
  utpcontrato in 'utpcontrato.pas' {frmtpcontrato},
  uimp_fluxo_caixa_realizado in 'uimp_fluxo_caixa_realizado.pas',
  uDlgEscolhePedido in 'uDlgEscolhePedido.pas' {frmdlgEscolhePedido},
  urpa in 'urpa.pas' {frmRPA},
  ulocalizarrpa in 'ulocalizarrpa.pas' {frmLocalizarRPA},
  YMOFXReader in 'YMOFXReader.pas',
  umanager in 'umanager.pas' {frmManager},
  udlggerarMovto in 'udlggerarMovto.pas' {frmdlgGerarMovto},
  uturno in 'uturno.pas' {frmTurno},
  classeInstrucaoSQL in 'classeInstrucaoSQL.pas',
  udlggerardevolucaosaida in 'udlggerardevolucaosaida.pas' {frmdglgerardevolucaosaida},
  usaidaexportaralterdatasaca in 'usaidaexportaralterdatasaca.pas',
  ulocalizarativopiscofins in 'ulocalizarativopiscofins.pas' {frmLocalizarAtivoPISCOFINS},
  utransportadora in 'utransportadora.pas' {frmTransportadora},
  unegociacao in 'unegociacao.pas' {frmnegociacao},
  ugrade in 'ugrade.pas' {frmgrade},
  ulocalizarnegociacao in 'ulocalizarnegociacao.pas' {frmLocalizarnegociacao},
  udlginutilizarcte in 'udlginutilizarcte.pas' {frmdlginutilizarcte},
  udlgSequenciaImpressao in 'udlgSequenciaImpressao.pas' {frmdlgsequenciaimpressao},
  udlgDetalheOrcamento in 'udlgDetalheOrcamento.pas' {frmdlgdetalheorcamento},
  udlgentradaproduto in 'udlgentradaproduto.pas' {frmdlgentradaproduto},
  classecteimportar in 'classecteimportar.pas',
  uctetransportadora in 'uctetransportadora.pas' {frmctetransportadora},
  uimp_pedidomaterial in 'uimp_pedidomaterial.pas',
  umanagerordproducao in 'umanagerordproducao.pas' {frmmanagerordproducao},
  uregrast in 'uregrast.pas' {frmRegrast},
  udlgchaveuso in 'udlgchaveuso.pas' {frmdlgchaveuso},
  ufiltrartarefa in 'ufiltrartarefa.pas' {frmFiltrarTarefa},
  udlgmetodoprocesso in 'udlgmetodoprocesso.pas' {frmdlgmetodoprocesso},
  udlgselecionarlista in 'udlgselecionarlista.pas' {frmdlgselecionarlista},
  utabela in 'utabela.pas' {frmTabela1},
  classerecalcularcomissao in 'classerecalcularcomissao.pas',
  classeimpressaoreport in 'classeimpressaoreport.pas',
  uprojeto in 'uprojeto.pas' {frmdlgProjeto},
  ufiltrarProjeto in 'ufiltrarProjeto.pas' {frmFiltrarProjeto},
  classegerarautpagto in 'classegerarautpagto.pas',
  utpordproducao in 'utpordproducao.pas' {frmtpordproducao},
  udlgsetavisotarefa in 'udlgsetavisotarefa.pas' {frmdlgsetavisotarefa},
  classetarefa in 'classetarefa.pas',
  udlgavisotarefa in 'udlgavisotarefa.pas' {frmdlgavisotarefa},
  uagenda in 'uagenda.pas' {frmagenda},
  uitagenda in 'uitagenda.pas' {frmdlgitagenda},
  classecopiarregistro in 'classecopiarregistro.pas',
  udlglocacaodevolucao in 'udlglocacaodevolucao.pas' {frmdlglocacaodevolucao},
  udlgtabela in 'udlgtabela.pas' {frmdlttabela},
  ulocalizaritagenda in 'ulocalizaritagenda.pas' {frmLocalizaritagenda},
  classeimportacaodados in 'classeimportacaodados.pas',
  udlgarquivo in 'udlgarquivo.pas' {frmdlgarquivo},
  uFastFunc in 'uFastFunc.pas',
  classeColumnField in 'classeColumnField.pas',
  classetabela in 'classetabela.pas',
  ureportuser in 'ureportuser.pas' {frmReportUser},
  uimp_movimentacaofinanceira in 'uimp_movimentacaofinanceira.pas',
  uimp_inventario_estoque in 'uimp_inventario_estoque.pas',
  uformulacao in 'uformulacao.pas' {frmFormulacao},
  uMenuRelatorio in 'uMenuRelatorio.pas' {DTModuleMenuRelat: TDataModule},
  classemdfe in 'classemdfe.pas',
  uLocalizarMDFE in 'uLocalizarMDFE.pas' {frmLocalizarMDFE},
  umdfereport in 'umdfereport.pas' {frmmdfereport},
  ucartacorrecaocte in 'ucartacorrecaocte.pas' {frmcartacorrecaocte},
  classecalculopeso in 'classecalculopeso.pas',
  classeregrast in 'classeregrast.pas',
  classerota in 'classerota.pas',
  ugrupo in 'ugrupo.pas' {frmgrupo},
  uconferenciapedido in 'uconferenciapedido.pas' {frmConferenciaPedido},
  uLocalizarConferenciaPedido in 'uLocalizarConferenciaPedido.pas' {frmLocalizarConferenciaPedido},
  classectegerar in 'classectegerar.pas',
  classeetiqueta in 'classeetiqueta.pas',
  classeimportacaocliente in 'classeimportacaocliente.pas',
  classeimportacaofornecedor in 'classeimportacaofornecedor.pas',
  ClasseImportacaoTransportadora in 'ClasseImportacaoTransportadora.pas',
  classeexportacaodatasulduplicata in 'classeexportacaodatasulduplicata.pas',
  classeexportacaodatasulcte in 'classeexportacaodatasulcte.pas',
  classeexportacaodatasulcontabil in 'classeexportacaodatasulcontabil.pas',
  ClasseExportacaoDatasulAutpagto in 'ClasseExportacaoDatasulAutpagto.pas',
  ClasseExportacaoDatasulMovto in 'ClasseExportacaoDatasulMovto.pas',
  ureportdesigner in 'ureportdesigner.pas' {frmreportdesigner},
  umetrologia in 'umetrologia.pas' {frmMetrologia},
  ulocalizarmetrologia in 'ulocalizarmetrologia.pas' {frmLocalizarMetrologia},
  uEquipamento in 'uEquipamento.pas' {frmEquipamento},
  uLocalizarEquipamento in 'uLocalizarEquipamento.pas' {frmLocalizarEquipamento},
  classeAplicacao in 'classeAplicacao.pas',
  ulocalizarformulacao in 'ulocalizarformulacao.pas' {frmLocalizarformulacao},
  uLocalizarDuplicata in 'uLocalizarDuplicata.pas' {frmLocalizarduplicata},
  uapontamento in 'uapontamento.pas' {frmapontamento},
  udlgapontamento in 'udlgapontamento.pas' {frmdlgapontamento},
  ulocalizarordserv in 'ulocalizarordserv.pas' {frmLocalizarOrdserv},
  udlgetiqueta in 'udlgetiqueta.pas' {frmdlgetiqueta},
  udlgLista in 'udlgLista.pas' {frmdlglista},
  classeapontamento in 'classeapontamento.pas',
  udlgtransferenciabancaria in 'udlgtransferenciabancaria.pas' {frmdlgtransferenciabancaria},
  udlggeraradiantamento in 'udlggeraradiantamento.pas' {frmdlgAdntcliente},
  udlggerarmovimentacao in 'udlggerarmovimentacao.pas' {frmdlgDespesa},
  udownload in 'udownload.pas' {frmdownload},
  uLocalizarPedidoMaterial in 'uLocalizarPedidoMaterial.pas' {frmLocalizarPedidoMaterial},
  classeautpagto in 'classeautpagto.pas',
  uautpagtoparcelamento in 'uautpagtoparcelamento.pas' {frmdlgGerarParcelamentoAutpagto},
  udlgGerarSaida in 'udlgGerarSaida.pas' {frmdlgGerarSaida},
  udlgtransferiradntcliente in 'udlgtransferiradntcliente.pas' {frmdlgtransferiradntcliente},
  udeclinarorcamento in 'udeclinarorcamento.pas' {frmdlgdeclinarorcamento},
  udlgaplicarconfiguracaogrupo in 'udlgaplicarconfiguracaogrupo.pas' {frmdlgaplicarconfiguracaogrupo},
  urequisicaoproducao in 'urequisicaoproducao.pas' {frmrequisicaoproducao},
  classerequisicaoproducao in 'classerequisicaoproducao.pas',
  ulocalizarrequisicaoproducao in 'ulocalizarrequisicaoproducao.pas' {frmLocalizarRequisicaoProducao},
  upontotrabalho in 'upontotrabalho.pas' {frmpontotrabalho},
  classeimportacaoiponto in 'classeimportacaoiponto.pas',
  classepontotrabalho in 'classepontotrabalho.pas',
  uloteserie in 'uloteserie.pas' {frmloteserie},
  ClasseRecalcularSaldoConta in 'ClasseRecalcularSaldoConta.pas',
  ueventoemail in 'ueventoemail.pas' {frmEventoEmail},
  classeeventoemail in 'classeeventoemail.pas',
  upaciente in 'upaciente.pas' {frmPaciente},
  ulocalizarpaciente in 'ulocalizarpaciente.pas' {frmLocalizarPaciente},
  uimp_funcionario_cesta_basica in 'uimp_funcionario_cesta_basica.pas',
  urhocorrencia in 'urhocorrencia.pas' {frmRHOcorrencia},
  ulocalizarrhocorrencia in 'ulocalizarrhocorrencia.pas' {frmLocalizarRHOcorrencia},
  unovopaciente in 'unovopaciente.pas' {frmNovoPaciente},
  classepaciente in 'classepaciente.pas',
  uimpmapafretemensal in 'uimpmapafretemensal.pas',
  uparada in 'uparada.pas' {frmparada},
  ulocalizarparada in 'ulocalizarparada.pas' {frmLocalizarParada},
  uimp_gratico_tpparada in 'uimp_gratico_tpparada.pas',
  uimp_grafico_pareto_tpparada in 'uimp_grafico_pareto_tpparada.pas',
  uprofissional in 'uprofissional.pas' {frmProfissional},
  usetchangetarefa in 'usetchangetarefa.pas' {frmsetchangetarefa},
  udlgclientefinanceiro in 'udlgclientefinanceiro.pas' {frmdlgclientefinanceiro},
  udlgduplicatacliente in 'udlgduplicatacliente.pas' {frmdlgduplicatacliente},
  udlghpedidoetapa in 'udlghpedidoetapa.pas' {frmdlghpedidoetapa},
  classeorcamentocopiar in 'classeorcamentocopiar.pas',
  utpresposta in 'utpresposta.pas' {frmTpResposta},
  utpcriterioorcamento in 'utpcriterioorcamento.pas' {frmtpcriterioorcamento},
  udlgjustificativa in 'udlgjustificativa.pas' {frmdlgjustificativa},
  uimp_ordproducaopesagem in 'uimp_ordproducaopesagem.pas',
  udlgordproducaopesagem in 'udlgordproducaopesagem.pas' {frmdlgordprodcaopesagem},
  udlgmapaproducaoproduto in 'udlgmapaproducaoproduto.pas' {frmdlgmapaproducaoproduto},
  uimp_pedidoatendimento in 'uimp_pedidoatendimento.pas',
  udlgtipo in 'udlgtipo.pas' {frmdlgTipo},
  classerecalcularpiscofins in 'classerecalcularpiscofins.pas',
  ucontratonegociacao in 'ucontratonegociacao.pas' {frmdlgGerarNegociacaoContrato},
  uembarque in 'uembarque.pas' {frmEmbarque},
  ULocalizarEmbarque in 'ULocalizarEmbarque.pas' {frmLocalizarEmbarque},
  ClasseEmbarque in 'ClasseEmbarque.pas',
  utpembarque in 'utpembarque.pas' {frmtpembarque},
  ClasseSerie in 'ClasseSerie.pas',
  uapontamentomanual in 'uapontamentomanual.pas' {frmApontamentoManual},
  ClasseApontamentoManual in 'ClasseApontamentoManual.pas',
  utpapontamentomanual in 'utpapontamentomanual.pas' {frmtpapontamentomanual},
  uLocalizarApontamentoManual in 'uLocalizarApontamentoManual.pas' {frmLocalizarApontamentoManual},
  ClasseCriterioReport in 'ClasseCriterioReport.pas',
  ClasseReport in 'ClasseReport.pas',
  ClasseTurma in 'ClasseTurma.pas',
  ClasseUF in 'ClasseUF.pas',
  ClasseMunicipio in 'ClasseMunicipio.pas',
  ClasseCest in 'ClasseCest.pas',
  udlgordcompraaprovacao in 'udlgordcompraaprovacao.pas' {frmdlgOrdcompraAprovacao},
  ClasseTpAprovacao in 'ClasseTpAprovacao.pas',
  ClasseGrupos in 'ClasseGrupos.pas',
  ClasseReportUser in 'ClasseReportUser.pas',
  ClasseFormulacao in 'ClasseFormulacao.pas',
  uworkbox in 'uworkbox.pas' {frmWorkBox},
  utpcorrecao in 'utpcorrecao.pas' {frmtpcorrecao},
  ClasseTpCorrecao in 'ClasseTpCorrecao.pas',
  ClasseCFOP in 'ClasseCFOP.pas',
  ClassePais in 'ClassePais.pas',
  ClasseRHOcorrencia in 'ClasseRHOcorrencia.pas',
  ClasseTpCobranca in 'ClasseTpCobranca.pas',
  ClasseTpFrete in 'ClasseTpFrete.pas',
  ClasseCalculoPrestacao in 'ClasseCalculoPrestacao.pas',
  udlgCalculoPrestacao in 'udlgCalculoPrestacao.pas' {frmdlgCalculoPrestacao},
  ClassePeriodicidade in 'ClassePeriodicidade.pas',
  uimp_consultaprodutoconsumo in 'uimp_consultaprodutoconsumo.pas',
  uconsultaProdutoImprimirFichaMovimentacao in 'uconsultaProdutoImprimirFichaMovimentacao.pas' {frmconsultaProdutoImprimirFichaMovimentacao},
  uconsultaProdutoImprimirMovimentoAnalitico in 'uconsultaProdutoImprimirMovimentoAnalitico.pas' {frmconsultaProdutoImprimirMovimentoAnalitico},
  uconsultaprodutoimprimirfichamovimentacaoterceiro in 'uconsultaprodutoimprimirfichamovimentacaoterceiro.pas' {frmconsultaProdutoImprimirFichaMovimentacao1},
  uconsultaprodutoestoquediario in 'uconsultaprodutoestoquediario.pas' {frmconsultaProdutoImprimirEstoquediario},
  uconsultasaidaImprimirFreteMensaluf in 'uconsultasaidaImprimirFreteMensaluf.pas' {frmconsultasaidaImprimirFreteMensaluf},
  uconsultasaidareferenciacruzada in 'uconsultasaidareferenciacruzada.pas' {frmconsultasaidareferenciacruzada},
  uconsultasaidaImprimirMensalProdutoPM in 'uconsultasaidaImprimirMensalProdutoPM.pas' {frmconsultasaidaImprimirMensalProdutoPM},
  uconsultasaidaImprimirMensalProdutoPP in 'uconsultasaidaImprimirMensalProdutoPP.pas' {frmconsultasaidaImprimirMensalProdutoPP},
  ClasseORM in 'ClasseORM.pas',
  ClasseDAO in 'ClasseDAO.pas',
  ClasseConection in 'ClasseConection.pas',
  ClasseWorkBox in 'ClasseWorkBox.pas',
  ClasseManagerAutpagto in 'ClasseManagerAutpagto.pas',
  ClasseSTICMS in 'ClasseSTICMS.pas',
  ClasseNFSE in 'ClasseNFSE.pas',
  ClasseConexao in 'ClasseConexao.pas',
  ClasseImpressaoMatricial in 'ClasseImpressaoMatricial.pas',
  ClasseLp1a in 'ClasseLp1a.pas',
  ClasseAtivoPisCofins in 'ClasseAtivoPisCofins.pas',
  ClasseProdutoFGerarBaixaEstoqueSubProduto in 'ClasseProdutoFGerarBaixaEstoqueSubProduto.pas',
  utreinamento in 'utreinamento.pas' {frmTreinamento},
  ulocalizarTreinamento in 'ulocalizarTreinamento.pas' {frmLocalizarTreinamento},
  ulocalizardespesaconvenio in 'ulocalizardespesaconvenio.pas' {frmLocalizardespesaconvenio},
  ClasseLocalizar in 'ClasseLocalizar.pas',
  uReport074DRE in 'uReport074DRE.pas',
  uimprimir643fatura in 'uimprimir643fatura.pas',
  ClasseBoletoAcbr in 'ClasseBoletoAcbr.pas',
  ClasseNegociacao in 'ClasseNegociacao.pas',
  ClasseImportacaoDOVerleih in 'ClasseImportacaoDOVerleih.pas',
  udespesaconvenio in 'udespesaconvenio.pas' {frmdespesaconvenio},
  ClasseImportacaoSenior in 'ClasseImportacaoSenior.pas',
  uordserv in 'uordserv.pas' {frmOrdServ},
  uOrdCompra in 'uOrdCompra.pas' {frmOrdCompra},
  utransporte in 'utransporte.pas' {frmtransporte},
  umdfe in 'umdfe.pas' {frmmdfe},
  urelease in 'urelease.pas' {frmRelease},
  ClasseImportarInventario in 'ClasseImportarInventario.pas',
  ClasseGerarCustoMedioLivroProducao in 'ClasseGerarCustoMedioLivroProducao.pas',
  ClasseImportacaoXML in 'ClasseImportacaoXML.pas',
  classeimportacaoGesoft in 'classeimportacaoGesoft.pas';

{$R *.res}

begin
  if (ParamStr(1) <> 'n') and // parametro para n perguntar quando faz atualizacao do banco de dados
     (not ContinuarAplicacaoMaisdeUmaInstancia) then // se já houver uma instância da aplicação funcionando
  begin
    exit;
  end;
  Windows.DeleteFile(_atualizacao+'.'+_exe);
  qrotinas.SetDecimalSeparator;
  dtmMain            := TDtmMain.Create(application);
  vgChaveAplicacao := _QUIPOS;
  aplicacao          := TAplicacao.create(dtmmain.sqlc, dtmmain.confire, vgChaveAplicacao);
  acbr               := TACBR.create;
  qp_nmcomputador    := nomedocomputador;
  try
    if not efetuarLogin then
    begin
      exit;
    end;
    Application.Initialize;
    Application.Title         := 'Quipos';
    Application.HintHidePause := 20000;
    Application.CreateForm(Tfrmmain, frmmain);
  acbr.lerconfiguracao;
    application.run;
  finally
    FreeAndNil(dtmMain);
    FreeAndNil(empresa);
    FreeAndNil(aplicacao);
    freeandnil(acbr);
    FreeAndNil(usuario);
  end;
end.
